YoYo-Web-App/Models/Yoyo/ActionType.cs
namespace YoYo_Web_App.Models.Yoyo
{
    public enum ActionType
    {
        Completed = 1, //stopped
        Warned = 2
    }
}

YoYo-Web-App/Models/Yoyo/IYoyoRepository.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using YoYo_Web_App.ViewModels;

namespace YoYo_Web_App.Models.Yoyo
{
    public interface IYoyoRepository
    {
        Task<YoyoViewModel> GetViewModelAsync();
        Task<IEnumerable<BeepTestData>> GetBeepTestData();
        AthleteInfo UpdateAthleteStatus(int id, ActionType type, LevelShuttleDetail levelShuttleDetail);
        TestCompletedResponse OnTestCompleted(IEnumerable<LevelShuttleDetails> levelShuttleDetails);
        IEnumerable<AthleteInfo> ViewResult();
    }
}

YoYo-Web-App/Models/Yoyo/LevelShuttleDetail.cs
namespace YoYo_Web_App.Models.Yoyo
{
    public class LevelShuttleDetail
    {
        public string Level { get; set; }
        public string Shuttle { get; set; }
    }
}

YoYo-Web-App/Models/Yoyo/LevelShuttleDetails.cs
namespace YoYo_Web_App.Models.Yoyo
{
    public class LevelShuttleDetails
    {
        public LevelShuttleDetail LevelShuttleDetail { get; set; }
        public int Id { get; set; }
    }
}

YoYo-Web-App/Models/Yoyo/TestCompletedResponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace YoYo_Web_App.Models.Yoyo
{
    public class TestCompletedResponse
    {
        public IEnumerable<AthleteInfo> AthleteInfos { get; set; }
        public bool IsValid { get; set; }
    }
}

YoYo-Web-App/Models/Yoyo/YoyoRepository.cs
using AutoMapper;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using YoYo_Web_App.Mapper;
using YoYo_Web_App.Models.AppConfig;
using YoYo_Web_App.ViewModels;

namespace YoYo_Web_App.Models.Yoyo
{
    /// <summary>
    /// The YoyoRepository contains 
    /// logic for all yoyo controller action methods
    /// </summary>
    public class YoyoRepository : IYoyoRepository
    {
        private readonly IAppConfig _appConfig;
        private readonly IMapper _mapper;
        private IEnumerable<BeepTestData> beepTestDatas;
        private IEnumerable<AthleteInfo> athleteInfos;

        /// <summary>
        /// The Repository constructor.
        /// </summary>
        /// <param name="appConfig">Contains application configuration</param>
        /// <param name="mapper">Contains mapper configuration</param>
        public YoyoRepository(IAppConfig appConfig, IMapper mapper)
        {
            _appConfig = appConfig;
            _mapper = mapper;
        }

        /// <summary>
        /// This method contains logic to get athletes and beep test json template data to load yoyo page .
        /// </summary>
        /// <returns>YoyoViewModel</returns>
        public async Task<YoyoViewModel> GetViewModelAsync()
        {
            beepTestDatas = await GetBeepTestData();
            athleteInfos = await GetAthletesInfo();
            if (beepTestDatas != null && athleteInfos != null)
                return _mapper.Map<IEnumerable<AthleteInfo>, YoyoViewModel>(athleteInfos)
                                .Map(GenerateLevelShuttleList(beepTestDatas), _mapper);
            return null;
        }

        /// <summary>
        /// This method reads beep test data from given json file. 
        /// </summary>
        /// <returns>IEnumerable of BeepTestData</returns>
        public async Task<IEnumerable<BeepTestData>> GetBeepTestData()
        {
            if (beepTestDatas != null && beepTestDatas.Count() > 0)
            {
                return beepTestDatas;
            }
            else
            {
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), _appConfig?.BeepTestFilePath ?? "wwwroot\\beepTestFile\\fitnessrating_beeptest.json");
                if (!File.Exists(filePath))
                    return null;
                var fs = File.OpenRead(filePath);
                return await JsonSerializer.DeserializeAsync<IEnumerable<BeepTestData>>(fs);
            }
        }
        /// <summary>
        /// This method contains logic to read athletes info from  athletes_info json file.
        /// </summary>
        /// <returns>IEnumerable of AthleteInfo</returns>
        private async Task<IEnumerable<AthleteInfo>> GetAthletesInfo()
        {
            var filePath = Path.Combine(Directory.GetCurrentDirectory(), _appConfig?.AthletesFilePath ?? "wwwroot\\beepTestFile\\athletes_info.json");
            if (!File.Exists(filePath))
                return null;
            var fs = File.OpenRead(filePath);
            return await JsonSerializer.DeserializeAsync<IEnumerable<AthleteInfo>>(fs);
        }

        /// <summary>
        /// This method contains logic to generate Level, Shuttle for dropdown. 
        /// </summary>
        /// <param name="beepTestDatas">List of Beep Test Data</param>
        /// <returns>IEnumerable of SelectListItem</returns>
        private IEnumerable<SelectListItem> GenerateLevelShuttleList(IEnumerable<BeepTestData> beepTestDatas)
        {
            return beepTestDatas.Select(a => new SelectListItem() { Value = $"{a?.SpeedLevel}-{a?.ShuttleNo}", Text = $"{a?.SpeedLevel}-{a?.ShuttleNo}" });
        }
        /// <summary>
        /// This method contains logic to save warned/stopped athletes
        /// </summary>
        /// <param name="id">Unique athlete ID</param>
        /// <param name="type">Type of action Warned/Completed(Stopped)()</param>
        /// <param name="levelShuttleDetail">Contains Level Shuttle Detail</param>
        /// <returns>successfully updated AthleteInfo</returns>
        public AthleteInfo UpdateAthleteStatus(int id, ActionType type, LevelShuttleDetail levelShuttleDetail)
        {
            var athleteInfo = athleteInfos.FirstOrDefault(a => a?.Id == id);
            if (athleteInfo != null)
            {
                switch (type)
                {
                    case ActionType.Completed:
                        {
                            athleteInfo.Completed = levelShuttleDetail;
                            break;
                        }
                    case ActionType.Warned:
                        {
                            athleteInfo.Warned = levelShuttleDetail;
                            break;
                        }
                }
                return athleteInfo;
            }
            return null;
        }
        /// <summary>
        /// This method contains logic to save list of athletes level, shuttle details.
        /// </summary>
        /// <param name="levelShuttleDetails">Contains list of athletes id with stopped(completed) level, shuttle details</param>
        /// <returns>successfully saved list of athletes info</returns>
        public TestCompletedResponse OnTestCompleted(IEnumerable<LevelShuttleDetails> levelShuttleDetails)
        {
            var testCompletedResponse = new TestCompletedResponse()
            {
                IsValid = false
            };
            if (!ValidateLevelShuttleDetails(levelShuttleDetails))
                return testCompletedResponse;

            var UpdatedAthleteInfo = new List<AthleteInfo>();
            foreach (var levelShuttleDetail in levelShuttleDetails)
            {
                var athleteInfo = athleteInfos.FirstOrDefault(a => a?.Id == levelShuttleDetail?.Id);
                if (athleteInfo?.Completed == null)
                {
                    athleteInfo.Completed = levelShuttleDetail.LevelShuttleDetail;
                    UpdatedAthleteInfo.Add(athleteInfo);
                }
            }
            testCompletedResponse = new TestCompletedResponse()
            {
                IsValid = true,
                AthleteInfos = UpdatedAthleteInfo
            };
            return testCompletedResponse;
        }
        /// <summary>
        /// This method contains logic to validate all the athletes ids are valid or not.
        /// </summary>
        /// <param name="levelShuttleDetails">List of level shuttle details of athletes</param>
        /// <returns></returns>
        private bool ValidateLevelShuttleDetails(IEnumerable<LevelShuttleDetails> levelShuttleDetails)
        {
            var valid = true;
            foreach (var levelShuttleDetail in levelShuttleDetails)
            {
                var athleteInfo = athleteInfos.FirstOrDefault(a => a?.Id == levelShuttleDetail.Id);
                if (athleteInfo == null)
                {
                    valid = false;
                    break;
                }
            }
            return valid;
        }
        /// <summary>
        /// This method gets Athletes Info
        /// </summary>
        /// <returns>list of athleteInfo</returns>
        public IEnumerable<AthleteInfo> ViewResult()
        {
            return athleteInfos ?? null;
        }
    }
}

YoYo-Web-App/ViewModels/YoyoViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using YoYo_Web_App.Models;

namespace YoYo_Web_App.ViewModels
{
    public class YoyoViewModel
    {
        public IEnumerable<AthleteInfo> AthleteInfos { get; set; }
        public IEnumerable<SelectListItem> LevelShuttles { get; set; }
    }
}

YoYo-Web-App/Controllers/YoyoController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using YoYo_Web_App.Models.Yoyo;

namespace YoYo_Web_App.Controllers
{
    /// <summary>
    /// The Yoyo Controller
    /// Contains all action methods
    /// </summary>
    public class YoyoController : Controller
    {
        private readonly IYoyoRepository _yoyoRepository;

        /// <summary>
        /// The yoyo controller constructor.
        /// </summary>
        /// <param name="yoyoRepository">Contains yoyo repository object</param>
        public YoyoController(IYoyoRepository yoyoRepository)
        {
            _yoyoRepository = yoyoRepository;
        }
        /// <summary>
        /// This method called, when yoyo page is loaded/refreshed.
        /// </summary>
        /// <returns>yoyo view with list of athletes</returns>
        [HttpGet]
        public async Task<IActionResult> YoyoView()
        {
            var yoyoViewModel = await _yoyoRepository.GetViewModelAsync();
            if (yoyoViewModel != null)
                return View(yoyoViewModel);
            return View("~/Views/Yoyo/NoTestFoundView.cshtml");
        }
        /// <summary>
        /// This method called, when yoyo page is loaded/refreshed.
        /// </summary>
        /// <returns>list of beep test data</returns>
        [HttpGet]
        public async Task<IActionResult> GetBeepTestData()
        {
            var beepTestData = await _yoyoRepository.GetBeepTestData();
            if (beepTestData != null)
                return new JsonResult(beepTestData);
            return NotFound("Beep test file might be empty or not found");
        }
        /// <summary>
        /// This method called, when coach warned or stopped the athletes and updates 
        /// level, shuttle details of athletes respectively. It also called when coach changes the level, shuttle of stopped athletes
        /// </summary>
        /// <param name="id">The unique athlete id</param>
        /// <param name="actionType">Enum completed(stopped)/warned</param>
        /// <param name="levelShuttleDetail">Contains completed(stopped)/warned athletes level and shuttle details.</param>
        /// <returns>successfully updated stopped/warned athletesInfo </returns>
        [HttpPut]
        public IActionResult UpdateAthleteStatus(int id, ActionType actionType, [FromBody] LevelShuttleDetail levelShuttleDetail)
        {
            if (levelShuttleDetail == null)
                return BadRequest($"Invalid object value - levelShuttleDetail");

            var response = _yoyoRepository.UpdateAthleteStatus(id, actionType, levelShuttleDetail);

            if (response != null)
                return Ok(response);
            return NotFound($"Athlete id {id} is not found");
        }
        /// <summary>
        /// This method called, when shuttle time is over,it updates the last completed shuttle, level details of active athletes
        /// </summary>
        /// <param name="levelShuttleDetails">Contains list of athletes with completed level and shuttle details</param>
        /// <returns>successfully updated list of completed(stopped)/warned athletes</returns>
        [HttpPut]
        public IActionResult OnTestCompleted([FromBody] IEnumerable<LevelShuttleDetails> levelShuttleDetails)
        {
            if (levelShuttleDetails == null)
                return BadRequest($"Invalid object value - levelShuttleDetails");

            var response = _yoyoRepository.OnTestCompleted(levelShuttleDetails);

            if (!response.IsValid)
                return NotFound($"param - levelShuttleDetails might be null or  one or more athlete Id is invalid");
            return Ok(response);
        }
        /// <summary>
        /// This method called, when view result button is clicked
        /// </summary>
        /// <returns>List of athletes with updated stopped(completed)/warned details.</returns>
        [HttpGet]
        public IActionResult ViewResult()
        {
            var response = _yoyoRepository.ViewResult();
            if (response != null)
                return Ok(response);
            return NotFound($"Test result not found");
        }
    }
}

YoYo-Web-App/Views/Yoyo/NoTestFoundView.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>NoTestFoundView</title>
</head>
<body>
    <h1 style="text-align:center; vertical-align:middle;"> No JSON template or athlete file found!!</h1>
</body>
</html>

YoYo-Web-App/Views/Yoyo/YoyoView.cshtml
@model YoyoViewModel
@{
    ViewBag.Title = "YoYo Test";
}
@section styles{
    <link href="~/lib/custom/css/yoyo.css" asp-append-version="true" rel="stylesheet" />
}

<br />
<div class="container">
    <div class="sticky-top">
        <div class="row">
            <div class="col-12 col-sm-12">
                <button type="button" class="pull-left btn-back"><i class="fa fa-angle-left" aria-hidden="true"></i> <span>Back</span></button>
                <h1 class="page-title-header text-center">@ViewBag.Title</h1>
            </div>
        </div>
        <div class="div-progress-bar">
            <div class="row">
                <div class="col-12 col-sm-4">
                </div>
                <div class="col-12 col-sm-4">
                    <div class="progress-bar">
                        <div class="progress-bar-value">
                            <div style="display:none;" class="test-completed">
                                Test Completed
                            </div>
                            <div style="display:none;" class="test-inprogress">
                                <div id="divLevel"></div>
                                <div id="divShuttle"></div>
                                <div id="divSpeed"></div>
                            </div>
                            <div class="test-start" onclick="OnStartTest(null);">
                                <i class="fa fa-play" aria-hidden="true"></i>
                            </div>
                        </div>
                        <span class="progress-bar-left">
                            <span id="spnleft" class="div-progress-bar"></span>
                        </span>
                        <span class="progress-bar-right">
                            <span id="spnright" class="div-progress-bar"></span>
                        </span>
                    </div>
                </div>
                <div class="col-12 col-sm-4">
                </div>
            </div>
        </div>
        <div class="div-test-progress">
            <div class="row">
                <div class="col-4 col-sm-4 col-lg-4 text-center border-right">
                    <h4 class="test-status-tag">NEXT SHUTTLE</h4>
                    <p class="default-font-color"><span id="spnLeftTime">0:00</span>s</p>
                </div>
                <div class="col-4 col-sm-4 col-lg-4 text-center border-right">
                    <h4 class="test-status-tag">TOTAL TIME</h4>
                    <p class="default-font-color"><span id="spnTotalTime">0:00</span>m</p>
                </div>
                <div class="col-4 col-sm-4 col-lg-4 text-center">
                    <h4 class="test-status-tag">TOTAL DISTANCE</h4>
                    <p class="default-font-color"><span id="spnTotalDistance">0</span>m</p>
                </div>
            </div>
        </div>
        <div class="div-view-result">
            <br />
            <div class="row">
                <div class="col-12 col-sm-12 col-lg-12 text-center">
                    <button type="button" onclick="GetAthletesResult();" class="badge badge-curve badge-viewresult">View results</button>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-sm-12 col-lg-12">
                <h3 class="track-header">Track</h3>
            </div>
        </div>
    </div>
    <div class="div-table">
        <div class="row">
            <div class="col-12 col-sm-12 col-lg-12">
                <div class="table-responsive-sm">
                    <table id="tblAthletesInfo" class="table table-sm table-hover">
                        <tbody>
                            @{int index = 1;}
                            @foreach (var athlete in Model.AthleteInfos)
                            {
                                <tr>
                                    <td class="tbl-slno" scope="row"><strong>@index .</strong></td>
                                    <td class="tbl-name"><strong>@athlete.FullName</strong></td>
                                    <td class="tbl-warn">
                                        <button type="button" asp-controller="Yoyo" asp-action="UpdateAthleteStatus" asp-route-id="@athlete.Id" asp-route-actionType="Warned" onclick="OnAthleteWarned(this);" class="badge badge-curve badge-warn">Warn</button>
                                    </td>
                                    <td class="tbl-stop" user-id="@athlete.Id">
                                        <button type="button" asp-controller="Yoyo" asp-action="UpdateAthleteStatus" asp-route-id="@athlete.Id" asp-route-actionType="Completed" onclick="OnAthleteStopped(this);" class="badge badge-curve badge-stop">Stop</button>
                                        <div class="div-athlete-dropdown">
                                            @Html.DropDownList("levelShuttle", Model.LevelShuttles, null, new { @onchange = "OnChangelevelShuttle(this)" })
                                        </div>
                                    </td>
                                </tr>
                                index++;
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script src="~/lib/custom/js/yoyo.js" asp-append-version="true" type="text/javascript"></script>
}